### ISSUE TITLE
Update products data again

### ISSUE THREAD

**Issue by JohanDjarvKarltorp** [vattenbagarna/Backend#69]
**Pumps:**
- Change Artikelnr to Modell
- Pumpkurva values should be named 'x' and 'y' instead of 'lyfthöjd m' and 'lps' (makes it easier for new product page to save values)

**Pumpstationer:**
- Change pump name to match Modell name in Pump category
- Settle how many pumps Kompus 61,81,82 has

**Comment by JohanDjarvKarltorp** [comment]
Should each products also save base64 icon to use on map page?
If not, what happens when a user makes a new product in a category and tries to place that product on map?

**Comment by Glassinatorn** [comment]
Base64 has been moved to seperate issue
