### ISSUE TITLE
Allow content-type: application/json from browser

### ISSUE THREAD

**Issue by JohanDjarvKarltorp** [vattenbagarna/Backend#70]
- Currently when trying to send content-type: application/json a preflight request is sent and returns false from server and the browser refuses to send data (CORS settings).

map.html and newObject.html have to save data in json format and can not use x-www-form-urlencoded because every value is counted as a string (text) and ignore arrays/objects.

**Comment by SpaceLenore** [comment]
This will be solved by sending the header 'Access-Control-Allow-Headers' with the value 'Content-Type'.
I'll make sure to add this!
